-- Enable RLS
alter table if exists public.documents enable row level security;
alter table if exists public.document_permissions enable row level security;
alter table if exists public.comments enable row level security;

-- DOCUMENTS TABLE (If checks to prevent errors if already exists)
create table if not exists public.documents (
  id text primary key, -- client-side generated ID or uuid
  user_id uuid references auth.users not null,
  title text default 'Untitled Document',
  content text default '',
  is_public boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- DOCUMENT PERMISSIONS
create table if not exists public.document_permissions (
  id bigint generated by default as identity primary key,
  document_id text references public.documents(id) on delete cascade not null,
  user_email text not null,
  role text not null check (role in ('viewer', 'commenter', 'editor', 'owner')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(document_id, user_email)
);

-- COMMENTS
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  document_id text references public.documents(id) on delete cascade not null,
  user_id uuid references auth.users not null,
  user_email text not null,
  content text not null,
  selection_range jsonb, -- { start, end, text }
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- FEEDBACK (Optional, from previous analysis)
create table if not exists public.proedit_feedback (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  rating int,
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- HELPER FUNCTIONS (To avoid infinite recursion in RLS)
create or replace function public.is_document_owner(doc_id text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.documents
    where id = doc_id
    and user_id = auth.uid()
  );
$$;

create or replace function public.is_collaborator(doc_id text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.document_permissions
    where document_id = doc_id
    and user_email = auth.jwt()->>'email'
  );
$$;

-- POLICIES

-- Documents: 
-- 1. Owner can do anything
drop policy if exists "Users can CRUD their own documents" on public.documents;
create policy "Users can CRUD their own documents"
on public.documents for all
using (auth.uid() = user_id);

-- 2. Public read access
drop policy if exists "Any one can read public documents" on public.documents;
create policy "Any one can read public documents"
on public.documents for select
using (is_public = true);

-- 3. Shared access (Read)
drop policy if exists "Collaborators can view shared documents" on public.documents;
create policy "Collaborators can view shared documents"
on public.documents for select
using (is_collaborator(id));

-- 4. Shared access (Update - Editors only)
drop policy if exists "Editors can update shared documents" on public.documents;
create policy "Editors can update shared documents"
on public.documents for update
using (
  exists (
    select 1 from public.document_permissions
    where document_id = documents.id
    and user_email = auth.jwt()->>'email'
    and role = 'editor'
  )
);

-- Permissions:
-- 1. Owner can view/manage permissions
drop policy if exists "Owners can manage permissions" on public.document_permissions;
create policy "Owners can manage permissions"
on public.document_permissions for all
using (is_document_owner(document_id));

-- 2. Collaborators can view their own permissions (to know their role)
drop policy if exists "Collaborators can view their own permissions" on public.document_permissions;
create policy "Collaborators can view their own permissions"
on public.document_permissions for select
using (user_email = auth.jwt()->>'email');

-- 3. Collaborators can view all permissions for a doc they have access to
drop policy if exists "Collaborators can view all permissions for their docs" on public.document_permissions;
create policy "Collaborators can view all permissions for their docs"
on public.document_permissions for select
using (is_collaborator(document_id));

-- Comments:
-- 1. Anyone with access to the doc can Read comments
drop policy if exists "Collaborators can view comments" on public.comments;
create policy "Collaborators can view comments"
on public.comments for select
using (
  is_document_owner(document_id)
  or exists (select 1 from public.documents where id = comments.document_id and is_public = true)
  or is_collaborator(document_id)
);

-- 2. Anyone with access (except maybe generic public?) can Create comments
drop policy if exists "Collaborators can create comments" on public.comments;
create policy "Collaborators can create comments"
on public.comments for insert
with check (
  is_document_owner(document_id)
  or is_collaborator(document_id)
);

-- 3. Users can update/delete their OWN comments
drop policy if exists "Users can manage their own comments" on public.comments;
create policy "Users can manage their own comments"
on public.comments for all
using (auth.uid() = user_id);

-- 4. Owners can delete ANY comment
drop policy if exists "Doc owners can delete any comment" on public.comments;
create policy "Doc owners can delete any comment"
on public.comments for delete
using (is_document_owner(document_id));
